# Generated by Django 5.0.1 on 2024-03-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_add_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
